export {computeRationalVectorFromRationalDecimal} from "./fromDecimal"
export {computeRationalVectorFromRationalQuotient} from "./fromQuotient"
export {isRationalVectorRough, computeRoughRationalVector} from "./roughness"
export {isRationalVectorSmooth, computeRationalVectorSmoothness} from "./smoothness"
export {computeRationalVectorCopfr} from "./copfr"
export {computeRationalVectorSopfr} from "./sopfr"
export {isVectorRational} from "./typeGuards"
export {doForEachRationalVector} from "./doForEachVector"
export {computeRationalVectorFromRationalScaledVector} from "./fromScaledVector"
