// Keep this alphabetical so you can ensure no conflicts.

enum ScriptFlag {
    MAX_2_3_FREE_SOPFR = "+",
    MAX_2_3_FREE_COPFR = "#",
    SOS_MODE = "0",
    EXCLUDED_FIELDS = "1",
    SYNC = "2",
    MAX_ATE = "3",
    SECONDARY_COMMA_ZONES = "4",
    COMPLEXITY_SEARCH_ED = "5",
    COMPLEXITY_ONLY = "6",
    ACCIDENTAL = "7",
    ORDERED_FIELDS = "8",
    EXCLUSIVE = "9",
    MAX_AAS = "a",
    TABLE_FORMAT = "b",
    NO_COLOR = "c",
    UNDIRECTED_COMMA_NAME = "d",
    NO_MOOT = "e",
    FACTORING_MODE = "f",
    COMMA_NAME = "g",
    // "h" reserved for help
    INTEGER = "i",
    MAX_UNIT = "j",
    USE_KNOWN_POPULAR_2_3_FREE_CLASSES = "k",
    LOWER_BOUND = "l",
    MONZO = "m",
    MAX_N2D3P9 = "n",
    ONLY_TOP = "o",
    PRIME_LIMIT = "p",
    QUOTIENT = "q",
    USE_BEST_NOTATING_COMMAS = "r",
    SORT_BY = "s",
    LOG_TARGETS = "t",
    UPPER_BOUND = "u",
    UNABBREVIATED_COMMA_NAME = "v",
    NO_WRITE = "w",
    NO_TIME = "x",
    USE_LATE = "y",
    Z = "z",
}

export {
    ScriptFlag,
}
