export {clearLogFiles} from "./clear"
export {saveLog} from "./save"
export {setLogTargets} from "./set"
export {LogTarget, LogTargets} from "./types"
export {setupScriptAndIo} from "./setup"
export {ScriptFlag, ColorMethod} from "./types"
export {program} from "./program"
export {DEFAULT_SCRIPT_SETTINGS} from "./constants"
export {scriptSettings} from "./globals"
export {time, now} from "./time"
export {formatTableFromScript} from "./table"
