export { computeSuperVector, isVectorSub, isVectorSuper, invertVector, isVectorUnison } from "./direction"
export { sumVectors, subtractVectors, addVectors } from "./typedOperations"
export { areVectorsEqual } from "./comparison"
export { PrimeCount, Vector } from "./types"
export { EMPTY_VECTOR } from "./constants"
