import {Base} from "./types"

const BASE_2: Base = 2 as Base

const ADDITIVE_IDENTITY = 0
const MULTIPLICATIVE_IDENTITY = 1

const VALUE_BELOW_WHICH_ROUNDING_IMPLEMENTATION_BREAKS: number = 1 / 1000000

const RADIANS_TO_DEGREES = 180 / Math.PI
const DEGREES_TO_RADIANS = Math.PI / 180

export {
    ADDITIVE_IDENTITY,
    MULTIPLICATIVE_IDENTITY,
    VALUE_BELOW_WHICH_ROUNDING_IMPLEMENTATION_BREAKS,
    BASE_2,
    RADIANS_TO_DEGREES,
    DEGREES_TO_RADIANS,
}
