export {computeRationalDecimalCopfr} from "./copfr"
export {computeRationalDecimalCopf} from "./copf"
export {computeRationalDecimalFromRationalScamon} from "./fromScamon"
export {computeRationalDecimalGpf} from "./gpf"
export {isDecimalRational, isDecimalInteger} from "./typeGuards"
export {isIntegerDecimalSmooth, computeRationalDecimalSmoothness, computeIntegerDecimalSmoothness} from "./smoothness"
export {computeRoughIntegerDecimal, isIntegerDecimalRough} from "./roughness"
export {ceil, floor, integerDivide} from "./typedOperations"
