export { Decimal } from "./types"
export { computeDecimalFromVector } from "./fromVector"
export { areDecimalsEqual } from "./comparison"
export { mod, reciprocal, computeArithmeticMean } from "./typedOperations"
export { computeDecimalFromQuotient } from "./fromQuotient"
export { isDecimalSuper, isDecimalUnison, isDecimalSub, invertDecimal } from "./direction"
export { negate } from "./sign"
