export {Decimal} from "./types"
export {computeDecimalFromPev} from "./fromPev"
export {areDecimalsEqual} from "./comparison"
export {mod, reciprocal, computeArithmeticMean} from "./typedOperations"
export {computeDecimalFromQuotient} from "./fromQuotient"
export {isDecimalSuper, isDecimalUnison, isDecimalSub, invertDecimal} from "./direction"
